In [1]:
import tensorflow as tf
x = tf.random_uniform([5,5,32],0,2, dtype = tf.int32, seed = 0)

with tf.Session() as sess:
    tf.initialize_all_variables().run()
    print x.get_shape()
    print x.eval()


(5, 5, 32)
[[[1 1 0 1 1 0 1 0 1 1 1 0 1 0 1 0 1 1 1 0 1 1 0 0 1 1 0 1 1 1 1 0]
  [0 0 1 0 1 1 0 1 1 1 1 0 0 1 1 1 0 0 0 0 0 1 0 0 0 1 0 1 1 1 1 0]
  [1 1 1 1 0 1 1 0 1 0 0 1 0 1 0 1 1 1 0 1 1 1 0 1 1 1 0 1 1 1 1 0]
  [0 1 0 0 1 1 1 1 1 0 0 1 0 0 0 1 1 0 1 0 1 0 0 0 0 1 1 1 1 0 1 1]
  [0 1 1 1 0 1 1 0 1 1 1 0 0 0 0 1 0 1 1 0 1 0 0 1 1 0 0 1 1 0 0 0]]

 [[0 0 1 0 0 0 1 0 0 1 1 1 1 0 1 0 0 1 0 0 0 0 0 1 1 1 0 1 0 0 0 1]
  [0 0 0 1 0 0 1 0 1 1 1 0 1 0 1 1 0 0 0 0 0 0 1 1 0 0 1 1 1 1 1 1]
  [1 0 1 1 1 0 1 1 0 1 0 0 1 0 1 0 0 0 0 1 0 1 1 1 1 1 1 0 0 1 1 0]
  [1 0 1 1 0 0 0 0 1 0 1 0 1 1 0 0 1 1 1 1 0 1 0 1 0 0 1 1 1 0 1 0]
  [0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 0 1 0 0 1 1 1 0]]

 [[1 0 0 0 0 1 1 0 1 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 0 0 0 0 1 1 0 0]
  [1 0 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 1 1 1 1 1 0 0 0 1 1 1 0 1 1]
  [0 1 0 1 0 1 1 1 1 1 1 0 0 1 0 0 1 0 1 1 1 1 1 0 1 1 1 1 0 1 1 1]
  [1 1 1 1 0 1 1 0 1 0 0 1 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 0 1 0 0]
  [0 1 0 1 0 1 0 0 0 0 1 0 1 1 0 

[1 1 0 1 1 0 1 0 1 1 1 0 1 0 1 0 1 1 1 0 1 1 0 0 1 1 0 1 1 1 1 0 0 0 1 0 1
 1 0 1 1 1 1 0 0 1 1 1 0 0]
[0 0 0 2 2 0 2 2 2 0 2 0 0 0 2 0 2 2 2 0 2 2 2 2 0 2 0 2 2 0 0 0 2 2 0 0 2
 2 2 0 0 0 2 2 2 0 2 2 0 0]


Exception AssertionError: AssertionError() in <bound method InteractiveSession.__del__ of <tensorflow.python.client.session.InteractiveSession object at 0x7f368878b3d0>> ignored
