In [ ]:
#这里对一个黑白image（即一个通道）进行卷积操作。

In [ ]:
# data = tf.constant([[1.0,1,1,1],[1,1,1,1],[1,1,1,1],[1,1,1,1]]) 这里如果都是整数，tf.nn.con2d那里报错。

In [ ]:
#input data 是四个维度： 1. batch_size, 2: width 3. length 4. channels.
# filter 四个维度： 1. width 2. length. 3. the number of channels as input. 4. the number of channels as output

In [2]:
import tensorflow as tf
conv1_weights = tf.Variable(
  tf.truncated_normal([2,2,1,2],  # 2*2 filter, depth 2.
                      stddev=0.1,
                      seed=1))

In [6]:
data = tf.constant([[1.0,1,1,1],[1,1,1,1],[1,1,1,1],[1,1,1,1]])
print data.get_shape()
data = tf.reshape(data,[1,4,4,-1])
print data.get_shape()

(4, 4)
(1, 4, 4, 1)


In [18]:
conv = tf.nn.conv2d(data,
                      conv1_weights,
                      strides=[1, 1, 1, 1],
                      padding='SAME')
init = tf.initialize_all_variables()

Instructions for updating:
Use `tf.global_variables_initializer` instead.


In [24]:
with tf.Session() as sess:
    sess.run(init)
    conv_res, weights = sess.run([conv,conv1_weights])
    print conv_res, "\n"
    print weights

[[[[ 0.00572439  0.16790129]
   [ 0.00572439  0.16790129]
   [ 0.00572439  0.16790129]
   [-0.01716211  0.30954701]]

  [[ 0.00572439  0.16790129]
   [ 0.00572439  0.16790129]
   [ 0.00572439  0.16790129]
   [-0.01716211  0.30954701]]

  [[ 0.00572439  0.16790129]
   [ 0.00572439  0.16790129]
   [ 0.00572439  0.16790129]
   [-0.01716211  0.30954701]]

  [[-0.07459889  0.15838473]
   [-0.07459889  0.15838473]
   [-0.07459889  0.15838473]
   [-0.08113182  0.14845988]]]] 

[[[[-0.08113182  0.14845988]]

  [[ 0.00653294  0.00992484]]]


 [[[ 0.06396971  0.16108713]]

  [[ 0.01635356 -0.15157056]]]]


In [ ]:
# 这是把一个convolutional layer放到一个function中，包括relu和add bias
def conv_layer(self, x, W_shape, b_shape, name, padding='SAME'):
        W = self.weight_variable(W_shape)
        b = self.bias_variable([b_shape])
        return tf.nn.relu(tf.nn.conv2d(x, W, strides=[1, 1, 1, 1], padding=padding) + b)