In [1]:
import tensorflow as tf

In [ ]:
# source: http://stackoverflow.com/questions/35488717/confused-about-conv2d-transpose

In [ ]:
sess = tf.Session()
batch_size = 3
output_shape = [batch_size, 8, 8, 128]
strides = [1, 2, 2, 1]

input = tf.constant(0.1, shape=[batch_size, 4, 4, 4])
w = tf.constant(0.1, shape=[7, 7, 128, 4])

h1 = tf.nn.conv2d_transpose(input, w, output_shape=output_shape, strides=strides, padding='SAME')
print sess.run(h1)

In [ ]:
#理清 Input和Output的维度关系，如果

In [7]:
output_shape = [batch_size, 16, 16, 128]
strides = [1, 2, 2, 1]
w = tf.constant(0.1, shape=[7, 7, 128, 4])
output = tf.constant(0.1, shape=output_shape)
expected_l = tf.nn.conv2d(output, w, strides=strides, padding='SAME')
print expected_l.get_shape()

(3, 8, 8, 4)


In [ ]:
#walk_through_2

In [9]:
import numpy as np
import tensorflow as tf


# [batch, height, width, depth]
x_image = tf.placeholder(tf.float32,shape=[3,2])
x = tf.reshape(x_image,[1,3,2,1])

#Filter: W  [kernel_height, kernel_width, output_depth, input_depth]
W_cpu = np.array([[1,-1]],dtype=np.float32)
W = tf.Variable(W_cpu)
W = tf.reshape(W, [1,2,1,1])

strides=[1, 1, 1, 1]
padding='VALID'

y = tf.nn.conv2d_transpose(x, W, [1,3,3,1],strides, padding)

x_data = np.array([[1,-1],[2,2],[1,2]],dtype=np.float32)
with tf.Session() as sess:
    init = tf.initialize_all_variables()
    sess.run(init)

    x = (sess.run(x, feed_dict={x_image: x_data}))
    W = (sess.run(W, feed_dict={x_image: x_data}))
    y = (sess.run(y, feed_dict={x_image: x_data}))

    print "The shape of x:\t", x.shape, ",\t and the x.reshape(3,2) is :"
    print x.reshape(3,2)
    print ""

    print "The shape of x:\t", W.shape, ",\t and the W.reshape(1,2) is :"
    print W.reshape(1,2)
    print ""

    print "The shape of y:\t", y.shape, ",\t and the y.reshape(3,3) is :"
    print y.reshape(3,3)
    print ""

Instructions for updating:
Use `tf.global_variables_initializer` instead.
The shape of x:	(1, 3, 2, 1) ,	 and the x.reshape(3,2) is :
[[ 1. -1.]
 [ 2.  2.]
 [ 1.  2.]]

The shape of x:	(1, 2, 1, 1) ,	 and the W.reshape(1,2) is :
[[ 1. -1.]]

The shape of y:	(1, 3, 3, 1) ,	 and the y.reshape(3,3) is :
[[ 1. -2.  1.]
 [ 2.  0. -2.]
 [ 1.  1. -2.]]

