In [7]:
import numpy as np
 
# Create column (or array)
A  = np.random.random(size=(2,3))
 
# Save to file
np.save("./data/myarray.npy", A)
 
print ra

[[ 0.66847536  0.5328783   0.26605127]
 [ 0.73601835  0.7948633   0.88008237]]


In [8]:
# Read from file
B  = np.load("./data/myarray.npy")

In [9]:
B == A

array([[ True,  True,  True],
       [ True,  True,  True]], dtype=bool)