In [ ]:
Two kinds of meaning: to a boolean variable and to a number

In [7]:
~index

array([False, False, False, False, False,  True, False, False,  True, False], dtype=bool)

In [1]:
import numpy as np
arr = np.random.randint(5,size=(10,2))
index = arr[:,0]>1

In [2]:
arr[index]

array([[2, 2],
       [4, 2],
       [3, 1],
       [3, 1],
       [3, 3],
       [2, 1],
       [3, 1],
       [3, 3]])

In [3]:
arr[~index]

array([[1, 2],
       [1, 1]])

In [6]:
i=8
~i

-9