In [6]:
import numpy as np
w = np.ones((3,2))

In [9]:
print w

[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]


In [7]:
act=np.array([1,2,3])
print act.shape

(3,)


In [10]:
np.dot(act,w)

array([ 6.,  6.])

In [12]:
act[:,None].shape

(3, 1)

In [13]:
w*act[:,None]

array([[ 1.,  1.],
       [ 2.,  2.],
       [ 3.,  3.]])

In [14]:
import numpy as np
w = np.ones((3,2))
act=np.array([1,2,3])
print act.shape
print np.dot(act,w)
print w*act[:,None]

(3,)
[ 6.  6.]
[[ 1.  1.]
 [ 2.  2.]
 [ 3.  3.]]


In [15]:
print w
print act[:,None]

[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
[[1]
 [2]
 [3]]
