In [1]:
import numpy as np
array = np.array([[[0,2,3],[1,2,3]],[[0,2,1],[1,3,2]],[[0,1,1],[1,4,5]]])
print array.shape

print array[0,:,:]
print array[1,:,:]

(3, 2, 3)
[[0 2 3]
 [1 2 3]]
[[0 2 1]
 [1 3 2]]


In [5]:
truth = np.all(array==0,axis=0)
print truth

[[ True False False]
 [False False False]]


In [4]:
np.where(truth)

(array([0]), array([0]))