In [10]:
import numpy as np
import numpy as np
w = np.array(range(6)).reshape(2,3)
con = np.array([1,2,3])
print w
print w[:,con<3]
print con<3

[[0 1 2]
 [3 4 5]]
[[0 1]
 [3 4]]
[ True  True False]


In [9]:
print w

[[0 1 2]
 [3 4 5]]


In [8]:
w[:,con<3]

array([[0, 1],
       [3, 4]])

In [5]:
con<3

array([ True,  True, False], dtype=bool)