In [ ]:
# loop through the first dimension

In [3]:
import numpy as np

In [4]:
c = np.arange(24).reshape(2,3,4)

for r in c :
     print r

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [6]:
for r in c.swapaxes(2,0).swapaxes(1,2):
    print r

[[ 0  4  8]
 [12 16 20]]
[[ 1  5  9]
 [13 17 21]]
[[ 2  6 10]
 [14 18 22]]
[[ 3  7 11]
 [15 19 23]]


In [ ]:
# http://stackoverflow.com/questions/1589706/iterating-over-arbitrary-dimension-of-numpy-array
# 下面的方法快慢有别，对于loop through其它维度的情况

In [ ]:
python -m timeit -s 'import numpy; c = numpy.arange(24).reshape(2,3,4)' 'for r in c.swapaxes(2,0).swapaxes(1,2): u = r'
100000 loops, best of 3: 3.69 usec per loop

python -m timeit -s 'import numpy; c = numpy.arange(24).reshape(2,3,4)' 'for i in range(c.shape[2]): u = c[:,:,i]'
100000 loops, best of 3: 6.08 usec per loop

python -m timeit -s 'import numpy; c = numpy.arange(24).reshape(2,3,4)' 'for r in numpy.rollaxis(c, 2): u = r'
100000 loops, best of 3: 6.46 usec per loop