In [5]:
import numpy as np
A = np.arange(2*3).reshape((2,3))
B = np.arange(3*2).reshape((3,2))

In [6]:
print A, B

[[0 1 2]
 [3 4 5]] [[0 1]
 [2 3]
 [4 5]]


In [7]:
np.dot(A,B)

array([[10, 13],
       [28, 40]])

In [8]:
M = np.ones((9, 9))
V3 = np.ones((2, 9, 5))

In [12]:
np.empty((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])