In [ ]:
#默认是行

In [2]:
import numpy as np
a = np.random.random((2, 3))

In [3]:
a.shape

(2, 3)

In [4]:
x,y =a

In [6]:
print x
print a

[ 0.30044414  0.65191254  0.85683614]
[[ 0.30044414  0.65191254  0.85683614]
 [ 0.75843966  0.79020045  0.54856405]]


In [7]:
x,y = np.random.random((3,2)) # 这样不行

ValueError: too many values to unpack

In [8]:
x,y = np.random.random((3,2)).T