In [4]:
import numpy as np
X= np.random.rand(2,3,4)

In [16]:
X_pad = np.pad(X,((0,0),(1,2),(0,0)),'constant', constant_values = (0))

In [17]:
X_pad

array([[[ 0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.8081404 ,  0.49761626,  0.66320849,  0.86512605],
        [ 0.67025051,  0.73102748,  0.6037163 ,  0.61324795],
        [ 0.16849061,  0.40319736,  0.3564544 ,  0.19608908],
        [ 0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ]],

       [[ 0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.65116022,  0.1628192 ,  0.35313506,  0.33611226],
        [ 0.17797301,  0.44304359,  0.98121974,  0.09474758],
        [ 0.28856635,  0.03662648,  0.18080736,  0.97442767],
        [ 0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ]]])

In [29]:
a

array([ 0.17797301,  0.44304359,  0.98121974,  0.09474758])

In [28]:
a =X[1,1,:]

In [30]:
a[0:2]

array([ 0.17797301,  0.44304359])

In [31]:
a[2:4]

array([ 0.98121974,  0.09474758])