In [6]:
import numpy as np
arr = np.random.randint(5,size=(10,2))

In [7]:
arr

array([[1, 4],
       [0, 0],
       [1, 1],
       [3, 4],
       [3, 2],
       [2, 0],
       [4, 4],
       [1, 4],
       [3, 2],
       [1, 4]])

In [10]:
index = arr[:,0]>2

In [11]:
arr[index,:]

array([[3, 4],
       [3, 2],
       [4, 4],
       [3, 2]])

In [12]:
arr[~index,:]

array([[1, 4],
       [0, 0],
       [1, 1],
       [2, 0],
       [1, 4],
       [1, 4]])