In [1]:
import numpy as np 
arr = np.random.randint(6,size=(6,2))
print arr

[[0 4]
 [4 1]
 [3 4]
 [4 1]
 [5 2]
 [4 4]]


In [10]:
counts = arr[:,0]
#weights = np.array([float(count)/np.sum(counts) for count in counts])

In [11]:
weights

array([ 0.  ,  0.2 ,  0.15,  0.2 ,  0.25,  0.2 ])

In [18]:
np.average(arr, weights= weights,axis=0)

array([ 4.1,  2.3])